spring.datasource.url=jdbc:mysql://localhost:3306/shopsphere
spring.datasource.username=root
spring.datasource.password=123456

# cloud details
cloudinary.cloud_name=dgne2qnib
cloudinary.api_key=699431284492372
cloudinary.api_secret=I7YU-neTD0wkM_ydVU0n5D_Eqgg

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect